version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/user/web/staticfiles/
      - media_volume:/home/user/web/media/
    expose:
      - 8000
    restart: always
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/user/web/staticfiles/
      - media_volume:/home/user/web/media/
    ports:
      - 4344:80
    depends_on:
      - web
    links:
      - web:web
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

volumes:
  postgres_data:
  static_volume:
  media_volume:

