# Generated by Django 3.2.2 on 2022-05-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreceipt',
            name='from_branch',
        ),
        migrations.RemoveField(
            model_name='productreceipt',
            name='to_branch',
        ),
    ]
