from django.contrib.auth.views import LogoutView
from django.urls import path

from app import views

urlpatterns = (
    path("", views.Template.as_view(), name="director_home"),
    path("discount-card/", views.DiscountCardListView.as_view(), name="app_discount_card_list"),
    path("discount-card/create/", views.DiscountCardCreateView.as_view(), name="app_discount_card_create"),
    path("discount-card/detail/<int:pk>", views.DiscountCardDetailView.as_view(), name="app_discount_card_detail"),
    path("discount-card/update/<int:pk>", views.DiscountCardUpdateView.as_view(), name="app_discount_card_update"),
    path("product/b2b", views.ProductListView.as_view(), name="app_product_list"),
    path("product/b2c", views.ProductB2CListView.as_view(), name="app_product_b2c_list"),
    path("product/create/", views.ProductCreateView.as_view(), name="app_product_create"),
    path("product/detail/<int:pk>", views.ProductDetailView.as_view(), name="app_product_detail"),
    path("product/update/<int:pk>", views.ProductUpdateView.as_view(), name="app_product_update"),
    path("branch/b2b/", views.BranchTemplateViewB2B.as_view(), name="app_branch_residue_list_b2b"),
    path("branch/b2c/", views.BranchTemplateViewB2C.as_view(), name="app_branch_residue_list_b2c"),
    # path("branch/", views.BranchListView.as_view(), name="app_branch_list"),
    path("branch/create/", views.BranchCreateView.as_view(), name="app_branch_create"),
    path("branch/detail/<int:pk>", views.BranchDetailView.as_view(), name="app_branch_detail"),
    path("branch/update/<int:pk>", views.BranchUpdateView.as_view(), name="app_branch_update"),
    path("staff/", views.StaffListView.as_view(), name="app_staff_list"),
    path("staff/detail", views.StaffDetailTemplateView.as_view(), name="staff_detail"),
    path("staff/create/", views.StaffCreateView.as_view(), name="app_staff_create"),
    path("staff/detail/<int:pk>", views.StaffDetailView.as_view(), name="app_staff_detail"),
    path("staff/update/<int:pk>", views.StaffUpdateView.as_view(), name="app_staff_update"),
    path("cashbox", views.CashboxTemplateView.as_view(), name="cashbox"),
    path("income-account", views.IncomeAccountTemplateView.as_view(), name="income_account"),
    path("expense-account", views.ExpenseAccountTemplateView.as_view(), name="expense_account"),
    path("get-back-from-the-customer/b2b/", views.GetBackFromTheCustomerTemplateViewB2B.as_view(),
         name="get_back_from_the_customer_b2b"),
    path("get-back-from-the-customer/b2c/", views.GetBackFromTheCustomerTemplateViewB2C.as_view(),
         name="get_back_from_the_customer_b2c"),
    path("get-back-from-the-customer1", views.GetBackFromTheCustomer1TemplateView.as_view(),
         name="get_back_from_the_customer1"),
    path("get-back-from-the-customer2", views.GetBackFromTheCustomer2TemplateView.as_view(),
         name="get_back_from_the_customer2"),
    path("get-back-from-the-customer3", views.GetBackFromTheCustomer3TemplateView.as_view(),
         name="get_back_from_the_customer3"),

    path("goods-returned-from-dom-stroy", views.GoodsReturnedFromDomStroy.as_view(),
         name="goods_returned_from_dom_stroy"),
    path("income-and-expenses-of-goods", views.IncomeAndExpensesOfGoods.as_view(), name="income_and_expenses_of_goods"),
    path("written-off-goods", views.WrittenOffGoods.as_view(), name="written_off_goods"),
    path("income-analysis", views.IncomeAnalysis.as_view(), name="income_analysis"),
    path("goods-movement-analysis", views.GoodsMovementAnalysis.as_view(), name="goods_movement_analysis"),
    path("goods-movement-analysis/<int:pk>", views.GoodsMovementAnalysisEdit.as_view(),
         name="goods_movement_analysis_update"),
    path("realized-goods", views.RealizedGoods.as_view(), name="realized_goods"),
    path("contractors", views.ContractorsTemplateView.as_view(), name="contractors"),
    path("contractors", views.ContractorsDetailTemplateView.as_view(), name="contractors_detail"),
    path("delivery-report/b2b/", views.DeliveryReportTemplateViewB2B.as_view(), name="delivery_report_b2b"),
    path("delivery-report/b2c/", views.DeliveryReportTemplateViewB2C.as_view(), name="delivery_report_b2c"),
    path("delivery", views.DeliveryTemplateView.as_view(), name="delivery"),
    path("delivery/<int:pk>/", views.DeliveryDetailTemplateView.as_view(), name="delivery_detail"),
    path("on-the-given-discounts", views.OnTheGivenDiscounts.as_view(), name="on_the_given_discounts"),
    path("by-agents", views.ByAgents.as_view(), name="by_agents"),
    path("employee-salaries", views.EmployeeSalaries.as_view(), name="employee_salaries"),
    path("staff-additional-salary", views.StaffsAdditionalSalary.as_view(), name="staff_additional_salary"),
    path("staff-additional-salary/<int:pk>", views.StaffsAdditionalSalaryDetail.as_view(),
         name="staff_additional_salary"),
    path("form-two-on-the-scale", views.FormTwoOnTheScale.as_view(), name="form_two_on_the_scale"),
    path("the-final-financial-result", views.TheFinalFinancialResult.as_view(), name="the_final_financial_result"),
    path("revision", views.Revision.as_view(), name="revision"),
    path("customer-debt/b2c", views.CustomerDebtB2C.as_view(), name="customer_debt_b2c"),
    path("customer-debt/b2b", views.CustomerDebtB2B.as_view(), name="customer_debt_b2b"),

    path("customer-debt/detail", views.CustomerDebtDetail.as_view(), name="customer_debt_detail"),
    path("settings", views.SettingsCreateView.as_view(), name="settings"),
    path("rate-of-products", views.RateOfProducts.as_view(), name="rate_of_products"),
    path("residual-goods", views.ResidualGoods.as_view(), name="residual_goods"),
    path("analisis-of-goods-sold", views.AnalisisOfGoodsSold.as_view(), name="analisis_of_goods_sold"),
    path("order", views.Order.as_view(), name="order"),
    path("report", views.Report.as_view(), name="report"),
    path("invoice", views.Invoice.as_view(), name="invoice"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("login/", views.LoginView.as_view(), name="login"),
)



